### ISSUE TITLE
Source code contains windows CRLF line-ending, which break on unix

### ISSUE THREAD

**Issue by Riernar** [Kurohyou-Studios/k-scaffold#28]
In releases, the source code has been exported from Windows it seems, all files end with `\r\n` as line endings.

While this isn't visible most of the time, it breaks specifically in `cli.mjs`, where the `\r` is fed to `/usr/bin/env` on unix, given it is not a special character. Then `env` complains that it cannot find `node\r`, because the command is `node`.

https://stackoverflow.com/questions/37145150/are-there-any-side-effects-of-having-unix-line-endings-when-working-on-windows-m seems to be advocating for using unix-style `\n` in all source files, even on windows, by setting the IDE (VSCode ?) and git configured as such.

Of note, this specifically affects the release process. It could perhaps be fixed by having an action release the code on nodejs.

**Comment by Kurohyou** [comment]
Hmm, odd. My git setup shouldn't even allow windows line endings to survive a push.

**Comment by Kurohyou** [comment]
This is fixed with the NPM automation
