### ISSUE TITLE
NPM dependencies are outdated and have critical vulnberabilities

### ISSUE THREAD

**Issue by Riernar** [Kurohyou-Studios/k-scaffold#41]
The output of `npm runn full-install` loudly complains about many outdated dependencies and critical vulnerabilities in our dependencies.

**Comment by Kurohyou** [comment]
Fixed most of these. Those that are left are dev dependencies only and stem from sassdoc. sassdoc does not appear to have a version that does not have vulnerabilities. Currently, as these are only run by devs, I'm going to leave them in.
