### ISSUE TITLE
`npm run docs` tasks prints a lot of output tothe terminal

### ISSUE THREAD

**Issue by Riernar** [Kurohyou-Studios/k-scaffold#42]
The `npm run docs` prints a lot of output to the terminal, so much so that it overflows the default history buffer.
It looks like it is printing it's full JSON output to stdout. This should not be done, as it severly hinders debugging and reading of error messages

**Comment by Riernar** [comment]
Since that scripts seems to be the one run, we should make it respect the following UNIX convention:

- print message that are human-readable and for the user to STDERR
- print a computer-parsable output, in structured format (e.g. JSON) to STDOUT
- If a problem occurs, something fails or is abnormal etc..., exit code must be non-zero

**Comment by Kurohyou** [comment]
This should no longer be happening.
