### ISSUE TITLE
`npm run docs` prints error but has return code 0

### ISSUE THREAD

**Issue by Riernar** [Kurohyou-Studios/k-scaffold#43]
The `npm run docs` task prints errors to the terminal, but has return code 0, which indicates success. This prevents the CI from understanding that the command failed, and that the CI should be marked as failed.

A failed command or script must always return a non-zero return code to indicate failure.

Due to #42 , the errors are not easily seen. Redirecting stdout to a file allows seeing the stderr output: `npm run docs > doc.log`

**Comment by Kurohyou** [comment]
This should no longer be happening
