### ISSUE TITLE
Builder throws SCSS Parse error when no sheet or roll SFC is used

### ISSUE THREAD

**Issue by richranallo** [Kurohyou-Studios/k-scaffold#89]
When building an SFC-initialized instance that isn't yet using a sheet or roll SFC, the builder throws an error and stops rather than including the commented line that no SFC is used:
[shelloutput.txt](https://github.com/Kurohyou-Studios/k-scaffold/files/13121686/shelloutput.txt)

The[ `renderSASS`](https://github.com/Kurohyou-Studios/k-scaffold/blob/2c2de856bb6c98b5046bacc5d5aef91e6d3f5fa2/lib/render/renderSASS.js#L16) function tries to read `sfcStyles.sheet` and `sfcStyles.roll` but if neither of these is used, `sfcStyles` is undefined and neither property can be read.

**Comment by richranallo** [comment]
Proposed fix in #90

**Comment by Kurohyou** [comment]
#92 resolves this.
